export const SET_BOOKMARK = 'SET_BOOKMARK';
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK';
export const ADD_TO_READ_VERSE = 'ADD_TO_READ_VERSE';
export const SET_NOTIFICATION_TIME = 'SET_NOTIFICATION_TIME';
export const SET_TODAY_VERSES = 'SET_TODAY_VERSES';
export const SET_TODAY_READ_VERSES = 'SET_TODAY_READ_VERSES';
export const REMOVE_YESTERDAY_COMPLATED_VERSES = 'REMOVE_YESTERDAY_COMPLATED_VERSES'