export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_TRANSLATOR = 'CHANGE_TRANSLATOR';
export const CHANGE_COMMENTRATOR = 'CHANGE_COMMENTRATOR';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';